### ISSUE TITLE
useNFTs throws an error

### ISSUE THREAD

**Issue by 7flash** [thirdweb-dev/react#70] opened 2022-05-26 11:47 UTC
Code example:

```
  const NFTContract = useNFTCollection('0x64903fbd6eedaa7eeb5e79e24597a90e62a3de0c');
  const { data: nfts, isLoading, error } = useNFTs(NFTContract, { start: 0, count: 100 });

  useEffect(() => {
    console.log('nfts', nfts);
    console.log('error', error);
  }, [nfts, isLoading, error]);
```

Result: 

![image](https://user-images.githubusercontent.com/4569866/170481892-4ee24498-7cc6-475b-9e44-ae3028b82b21.png)

**Comment by jnsdls** [comment] 2022-05-26 16:24
hey @7flash, which chain is this nft collection on? I'd love to be able to reproduce this, it would massively help in tracking down the problem and fixing it! thanks!

**Comment by 7flash** [comment] 2022-05-27 07:59
Ethereum Mainnet..

**Comment by 7flash** [comment] 2022-05-27 08:00
> hey @7flash, which chain is this nft collection on? I'd love to be able to reproduce this, it would massively help in tracking down the problem and fixing it! thanks!


Ethereum Mainnet..

**Comment by jnsdls** [comment] 2022-05-27 09:21
@7flash ok, I took a look, here's what I have so far:
- the NFTs in this contract seem to be using a centralized server `https://metadata.ctr10000.com` to host the assets
- that server has `CORS` settings that block clients that are not on the same domain from accessing the metadata hosted there

The error being thrown in this case is definitely confusing but it looks to me like the underlying error is in the setup of the metadata / server configuration in this case. I'll leave this open for now because we do need to handle these errors when they happen better.

**Comment by jnsdls** [comment] 2022-06-02 22:21
assuming this is solved / explained. Closing. (Feel free to re-open if there are further questions.)

**Closed by jnsdls** 2022-06-02 22:21 UTC
Labels: question

**Comment by 7flash** [comment] 2022-06-03 00:09
But the collection above is being properly fetched by both Opensea API and Moralis API..

**Comment by jnsdls** [comment] 2022-06-03 00:11
> But the collection above is being properly fetched by both Opensea API and Moralis API..

yup, both of those use indexers (servers that aggregate all the data on-chain and store it in a traditional database) => then they read it from the database.

> Maybe because they are sending requests from the server.. and this library is sending request directly from the browser.. is that correct...

yep, this is indeed correct
